### ISSUE TITLE
Internal Server Error on https://inuka-dedicated.odoo.com/

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/Inuka-Dedicated#1]
When you attempt to access https://inuka-dedicated.odoo.com/ you get an internal server error. This was working fine on Friday, and dont know what happened to it for it to start giving this issue.

There are errors showing in the logs, please review this.

**Comment by mdi-odoo** [comment]
There is no issue with code. The error is due to odoo.sh service is under maintenance.
